$(FINAL_CONSTRDESTR_PDF): $(CONSTRDESTR_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(CONSTRDESTR_BASE) $(CONSTRDESTR_BASE)/slides.tex

$(FINAL_CONSTRDESTR_EJ_PDF):	$(CONSTRDESTR_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(CONSTRDESTR_BASE)-ej $(CONSTRDESTR_BASE)/ej/hoja-ej.tex
