$(FINAL_NOEXCEPT_PDF): $(NOEXCEPT_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(NOEXCEPT_BASE) $(NOEXCEPT_BASE)/slides.tex

$(FINAL_NOEXCEPT_EJ_PDF):	$(NOEXCEPT_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(NOEXCEPT_BASE)-ej $(NOEXCEPT_BASE)/ej/hoja-ej.tex
