$(FINAL_COPYMOVE_PDF): $(COPYMOVE_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(COPYMOVE_BASE) $(COPYMOVE_BASE)/slides.tex

$(FINAL_COPYMOVE_EJ_PDF):	$(COPYMOVE_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(COPYMOVE_BASE)-ej $(COPYMOVE_BASE)/ej/hoja-ej.tex
