$(FINAL_GENERIC_PDF): $(GENERIC_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(GENERIC_BASE) $(GENERIC_BASE)/slides.tex

$(FINAL_GENERIC_EJ_PDF):	$(GENERIC_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(GENERIC_BASE)-ej $(GENERIC_BASE)/ej/hoja-ej.tex
